#!/bin/bash

count="$1"

if [[ -z $count ]]; then
    count=1
fi

senderFingerprint="19E705AF02AA47A5840ED18219C2645A1B9A3127"
recipientFingerprint="E0BE5FDEAD10DBC2B0A5A43345E797DBEBBBEF75"

for ((num = 1; num <= $count; num++)); do
    message="scriptMessage$num"
    pipenv run python ../scmail.py send -s $senderFingerprint -r $recipientFingerprint -m $message
done
